import express from 'express';
import PDFDocument from 'pdfkit';
import archiver from 'archiver';
import prisma from '../config/db.js';
import authMiddleware from '../middleware/auth.js';
import rbac from '../middleware/rbac.js';
import logger from '../config/logger.js';

const router = express.Router();
router.use(authMiddleware);

// --- HELPER FUNCTION: THE PAYSLIP DESIGN WITH TENANT CUSTOMISATION ---
const generatePayslipPDF = (doc, item) => {
  const { employee, payrollRun } = item;
  const company = payrollRun.company;

  // Header: Company Branding
  if (company.logoUrl) {
    try {
      doc.image(company.logoUrl, 250, 40, { width: 100 }); // center top logo
      doc.moveDown(2);
    } catch (err) {
      logger.warn('Logo rendering failed', { companyId: company.id, error: err.message });
    }
  }

  doc.fillColor(company.themeColor || 'black')
     .fontSize(16)
     .font('Helvetica-Bold')
     .text(company.name.toUpperCase(), { align: 'center' });

  doc.fillColor('black')
     .fontSize(10)
     .font('Helvetica')
     .text(company.address || '', { align: 'center' });

  doc.text(`OFFICIAL PAYSLIP: ${payrollRun.month}`, { align: 'center' });
  doc.moveDown(2);

  // Employee Details
  doc.fontSize(10).text(`Employee: ${employee.name}`, 50);
  doc.text(`Position: ${employee.position}`, 50);
  doc.text(`Ghana Card: ${employee.ghanaCardPin || 'N/A'}`, 50);
  doc.text(`SSNIT No: ${employee.ssnitNumber || 'N/A'}`, 50);
  doc.moveDown();

  const drawLine = () => doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

  // Table Branding
  drawLine();
  doc.font('Helvetica-Bold').text('DESCRIPTION', 50, doc.y + 5);
  doc.text('AMOUNT (GHS)', 450, doc.y - 12, { align: 'right' });
  doc.moveDown(0.5);
  drawLine();
  doc.font('Helvetica').moveDown(0.5);

  // Earnings
  doc.text('Basic Salary', 50);
  doc.text(employee.basicSalary.toFixed(2), 450, doc.y - 12, { align: 'right' });

  const allowances = item.grossSalary - employee.basicSalary;
  if (allowances > 0) {
    doc.text('Total Allowances', 50);
    doc.text(allowances.toFixed(2), 450, doc.y - 12, { align: 'right' });
  }

  doc.font('Helvetica-Bold').text('GROSS SALARY', 50, doc.y + 5);
  doc.text(item.grossSalary.toFixed(2), 450, doc.y - 12, { align: 'right' });
  doc.moveDown(1.5);

  // Deductions
  doc.font('Helvetica').text('SSNIT Employee (5.5%)', 50);
  doc.text(item.ssnitEmployee.toFixed(2), 450, doc.y - 12, { align: 'right' });

  doc.text('Income Tax (PAYE)', 50);
  doc.text(item.payeTax.toFixed(2), 450, doc.y - 12, { align: 'right' });
  doc.moveDown(1);

  // Net Pay
  drawLine();
  doc.font('Helvetica-Bold').fontSize(12).text('NET PAYABLE', 50, doc.y + 10);
  doc.text(`GHS ${item.netPay.toFixed(2)}`, 450, doc.y - 14, { align: 'right' });
  doc.moveDown(2);
  drawLine();

  // Footer: Tenant Customisation
  doc.fontSize(8)
     .font('Helvetica-Oblique')
     .text(company.footerNote || 'Generated by Payroll System 2026. Secure Document.', { align: 'center' });
};

// --- ROUTE 1: SINGLE PAYSLIP DOWNLOAD ---
router.get(
  '/item/:itemId/pdf',
  rbac(['SUPER_ADMIN', 'ADMIN', 'HR', 'ACCOUNTANT', 'EMPLOYEE']),
  async (req, res) => {
    const { itemId } = req.params;
    try {
      const where = {
        id: itemId,
        payrollRun: req.userRole !== 'SUPER_ADMIN' ? { companyId: req.companyId } : {},
      };

      // Strict isolation: Employees can ONLY download their own payslip.
      if (req.userRole === 'EMPLOYEE') {
        where.employee = { userId: req.userId };
      }

      const item = await prisma.payrollItem.findFirst({
        where,
        select: {
          grossSalary: true, ssnitEmployee: true, payeTax: true, netPay: true,
          employee: { select: { name: true, position: true, ghanaCardPin: true, ssnitNumber: true, basicSalary: true, userId: true } },
          payrollRun: { select: { month: true, companyId: true, company: { select: { id: true, name: true, address: true, logoUrl: true, themeColor: true, footerNote: true } } } }
        }
      });

      if (!item) {
        logger.warn('Payslip PDF access denied or not found', { itemId, userId: req.userId, role: req.userRole });
        return res.status(404).json({ error: 'Payslip not found or access denied' });
      }

      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const filename = `payslip_${item.employee.name.replace(/\s+/g, '_').slice(0,50)}.pdf`;

      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename=${filename}`);

      doc.pipe(res);
      generatePayslipPDF(doc, item);
      doc.end();

      logger.info(`Payslip generated for ItemID ${itemId} by User ${req.userId}`, { role: req.userRole });
    } catch (error) {
      logger.error('Single Payslip Error', { itemId, role: req.userRole, stack: error.stack });
      res.status(500).json({ error: 'Failed to generate PDF' });
    }
  }
);

// --- ROUTE 2: BULK PAYSLIPS (ZIP) ---
router.get('/bulk/:runId/pdf', rbac(['SUPER_ADMIN', 'ADMIN', 'HR', 'ACCOUNTANT']), async (req, res) => {
  const { runId } = req.params;
  try {
    const items = await prisma.payrollItem.findMany({
      where: req.userRole === 'SUPER_ADMIN' 
        ? { payrollRunId: runId } 
        : { payrollRunId: runId, payrollRun: { companyId: req.companyId } },
      select: {
        grossSalary: true, ssnitEmployee: true, payeTax: true, netPay: true,
        employee: { select: { name: true, position: true, ghanaCardPin: true, ssnitNumber: true, basicSalary: true } },
        payrollRun: { select: { month: true, companyId: true, company: { select: { id: true, name: true, address: true, logoUrl: true, themeColor: true, footerNote: true } } } }
      }
    });

    if (!items.length) return res.status(404).json({ error: 'No records found for this payroll run' });

    // Defense-in-depth tenant check
    if (req.userRole !== 'SUPER_ADMIN') {
      const leaked = items.find((i) => i.payrollRun.companyId !== req.companyId);
      if (leaked) {
        logger.error('CRITICAL: Cross-tenant payslip leak prevented in bulk export', {
          runId, userId: req.userId, expectedCompany: req.companyId, foundCompany: leaked.payrollRun.companyId,
        });
        return res.status(403).json({ error: 'Access denied: Tenant mismatch' });
      }
    }

    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename=bulk_payslips_${runId}.zip`);

    const archive = archiver('zip', { zlib: { level: 5 } });
    archive.pipe(res);

    // FIXED (2026-07-06): Replaced fire-and-forget sync PDF loop with an asynchronous 
    // sequential promise pipeline. This blocks the stream loop until each binary payload is 
    // fully written to the zip disk, avoiding V8 heap allocation limits on big runs.
    for (const item of items) {
      await new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const chunks = [];

        doc.on('data', chunk => chunks.push(chunk));
        doc.on('end', () => {
          const buffer = Buffer.concat(chunks);
          const safeName = item.employee.name.replace(/[^a-z0-9]/gi, '_').toLowerCase().slice(0,50);
          archive.append(buffer, { name: `payslip_${safeName}.pdf` });
          resolve();
        });
        doc.on('error', (err) => reject(err));

        generatePayslipPDF(doc, item);
        doc.end();
      });
    }

    await archive.finalize();
    logger.info(`Bulk payslips generated for RunID ${runId} by User ${req.userId}`, { role: req.userRole });
  } catch (error) {
    logger.error('Bulk Payslips Error', { runId, role: req.userRole, stack: error.stack });
    if (!res.headersSent) res.status(500).json({ error: 'Failed to generate zip archive' });
  }
});

export default router;